###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    webserver:
        image: 'nginx:alpine'
        container_name: kanye-quotes-webserver
        working_dir: /var/www/html
        volumes:
            - '.:/var/www/html'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '80:80'

    php-fpm:
        build: phpdocker/php-fpm
        container_name: kanye-quotes
        working_dir: /var/www/html
        volumes:
            - '.:/var/www/html'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
        ports:
            - '9000:9000'
